# Site settings
title: EWINIA
email: info@ewinia.com
url: https://ewinia.com
description: EWINIA will raise Mountainous Waves in Online and Mobile App Markets. It is in Ewinia’s DNA that Game is not enough. It is Game married with the Education.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#1428a0'
  links: '#ffffff'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/EWINIA_COM
  - title: facebook
    url: https://www.facebook.com/pages/Ewinia/1444460305865853
  - title: google-plus
    url: http://google.com/+EwiniaDotCom

# Build settings
markdown: kramdown
permalink: pretty
